### ISSUE TITLE
Discriminated Unions

### ISSUE THREAD

**Issue by ryskajakub** [esamattis/react-zorm#30]
https://codesandbox.io/s/zen-pond-2k8ugn?file=/src/App.tsx

It looks like it is not possible to work with union type right now. I would like to have some input with `type` field and based on this type, different sets of data could be submitted. But the other fields specific to each type can't be accessed in the field chains.

**Comment by medv** [comment]
Relevant issue with discussion on the problem scope from react-hook-form https://github.com/react-hook-form/react-hook-form/issues/8815

**Comment by esamattis** [comment]
This happens because the union is not "discriminated" on the chains and it's not really possible to do in userland.

In theory we could flatten out the union but it would not work when unions have same keys with different types. Like what to do on the chain when a field is an array and object on the other?

But this something you can actually do in userland, although it is bit awkward. Just split the discriminants to separate schemas and use `.merge()` on the form and parse it back to discriminated union afterwards.

Codesandbox https://codesandbox.io/s/vibrant-hoover-ez5vh6?file=/src/App.tsx:114-646

```ts
const Type1 = z.object({ type: z.literal("type1"), data1: z.string() });
const Type2 = z.object({ type: z.literal("type2"), data2: z.string() });

const UnionSchema = z.discriminatedUnion("type", [Type1, Type2]);

const FormSchema = z.object({
  // ...
  data: Type1.merge(Type2).merge(
    // Need to override the `type` here to be more generic.
    // Could use normal union here as well.
    z.object({
      type: z.string()
    })
  )
});
```

Other options would be to model the problem as different forms or just nested objects with custom refines.

Codesandbox https://codesandbox.io/s/recursing-fast-cn0mwb?file=/src/App.tsx


```ts
const FormSchema = z
  .object({
    type1: z
      .object({
        data1: z.string(),
        other1: z.string()
      })
      .optional(),
    type2: z
      .object({
        data2: z.string(),
        other2: z.string()
      })
      .optional()
  })
  .refine(
    (val) => {
      return !isEmpty(val.type1) || !isEmpty(val.type2);
    },
    { message: "type1 or type2 must be defined" }
  );
```

**Comment by esamattis** [comment]
Closing since I don't see there's is any action we could take on React Zorm side. Feel free to continue the discussion. We can of course reopen if good ideas for React Zorm comes up.
